language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
notifications:
  email: false
cache:
  directories:
    - node_modules
    - build
script: 
  - npm install
  - npm i -g nexe
  - nexe

